# Funding sources for Monster Spawned Studios:
github: [Monster-Spawned-Studios]
patreon: MonsterSpawnedStudios
ko_fi: MonsterSpawnedStudios``
custom: [https://monsterspawned.studio/donate, https://cash.app/$MonsterSpawned]
