#!/usr/bin/env python3
"""
Generate API reference and extension API markdown from source.

Invoked by scripts/build_docs.py from the project root. Can also be run directly:

    python docs/scripts/generate_api_docs.py

(From project root.) Writes docs/api-reference/endpoints.md and docs/extension-api/nsfw-guard-api.md.
Uses regex and ast only; does not import ComfyUI or mss-login.
"""

from __future__ import annotations

import ast
import os
import re
from pathlib import Path

# Project root: this file is docs/scripts/generate_api_docs.py -> parent.parent = docs, parent.parent.parent = root
ROOT = Path(__file__).resolve().parent.parent.parent
DOCS = ROOT / "docs"
ROUTES_DIR = ROOT / "routes"
API_MODULE_PATH = ROOT / "api.py"


def _extract_routes_from_file(filepath: Path) -> list[tuple[str, str, str, str]]:
	"""Extract (method, path, handler_name, docstring) from a route file."""
	text = filepath.read_text(encoding="utf-8")
	entries: list[tuple[str, str, str, str]] = []
	pattern = re.compile(
		r"@routes\.(get|post|put|delete)\s*\(\s*([\"'])(.+?)\2\s*\)\s*\n"
		r"(?:(?:.*?\n)*?)(?:async\s+)?def\s+(\w+)\s*\(",
		re.MULTILINE | re.DOTALL,
	)
	for m in pattern.finditer(text):
		method = m.group(1).upper()
		path = m.group(3)
		handler = m.group(4)
		after = text[m.end() : m.end() + 300]
		doc_match = re.search(r'(\s*)("""[\s\S]*?"""|\'\'\'[\s\S]*?\'\'\')', after)
		doc = ""
		if doc_match:
			raw = doc_match.group(2)
			doc = raw.strip("\"'").strip()
			if "\n" in doc:
				doc = doc.split("\n")[0].strip()
			if len(doc) > 100:
				doc = doc[:97] + "..."
		entries.append((method, path, handler, doc))
	return entries


def generate_endpoints_md() -> None:
	"""Write docs/api-reference/endpoints.md from routes/*.py."""
	route_files = [
		("Auth", "auth.py"),
		("Admin", "admin.py"),
		("User", "user.py"),
		("MFA", "mfa.py"),
		("Me", "me.py"),
		("Recovery", "recovery.py"),
	]
	all_entries: list[tuple[str, str, str, str, str]] = []
	for group, filename in route_files:
		path = ROUTES_DIR / filename
		if not path.exists():
			continue
		for method, path_val, handler, doc in _extract_routes_from_file(path):
			all_entries.append((group, method, path_val, handler, doc))

	out_path = DOCS / "api-reference" / "endpoints.md"
	out_path.parent.mkdir(parents=True, exist_ok=True)
	lines = [
		"# HTTP Endpoints",
		"",
		"Generated by `scripts/build_docs.py` from the route modules.",
		"",
		"| Group | Method | Path | Handler | Description |",
		"|-------|--------|------|---------|-------------|",
	]
	for group, method, path_val, handler, doc in all_entries:
		desc = (doc or "").replace("|", "\\|").replace("\n", " ").strip()[:80]
		lines.append(f"| {group} | {method} | `{path_val}` | `{handler}` | {desc} |")
	lines.extend(["", "---", "", "*Run `python scripts/build_docs.py` to regenerate.*"])
	out_path.write_text("\n".join(lines), encoding="utf-8")


def _extract_api_public() -> list[tuple[str, str, str]]:
	"""Extract (name, signature_summary, docstring) for public API from api.py using ast."""
	src = API_MODULE_PATH.read_text(encoding="utf-8")
	tree = ast.parse(src)
	__all__: list[str] = []
	funcs: dict[str, ast.FunctionDef] = {}
	for node in ast.walk(tree):
		if isinstance(node, ast.Assign):
			for t in node.targets:
				if isinstance(t, ast.Name) and t.id == "__all__":
					if isinstance(node.value, ast.List):
						for e in node.value.elts:
							if isinstance(e, ast.Constant):
								__all__.append(e.value)
							elif isinstance(e, ast.Str):
								__all__.append(e.s)
		if isinstance(node, ast.FunctionDef):
			funcs[node.name] = node
	result: list[tuple[str, str, str]] = []
	for name in __all__:
		if name.startswith("_"):
			continue
		fn = funcs.get(name)
		if not fn:
			continue
		args = []
		num_defaults = len(fn.args.defaults) if fn.args.defaults else 0
		num_args = len(fn.args.args)
		for i, a in enumerate(fn.args.args):
			if a.arg == "self":
				continue
			if num_defaults and i >= num_args - num_defaults:
				default_node = fn.args.defaults[i - (num_args - num_defaults)]
				if isinstance(default_node, ast.Constant):
					args.append(f"{a.arg}={default_node.value!r}")
				else:
					args.append(f"{a.arg}=...")
			else:
				args.append(a.arg)
		sig = f"{name}({', '.join(args)})"
		doc = ast.get_docstring(fn) or ""
		result.append((name, sig, doc))
	return result


def generate_nsfw_guard_api_md() -> None:
	"""Write docs/extension-api/nsfw-guard-api.md from api.py."""
	entries = _extract_api_public()
	out_path = DOCS / "extension-api" / "nsfw-guard-api.md"
	out_path.parent.mkdir(parents=True, exist_ok=True)
	lines = [
		"# NSFW Guard API",
		"",
		"Public Python API for other ComfyUI extensions to use NSFW detection and enforcement.",
		"",
		"## Import",
		"",
		"```python",
		"try:",
		"    from ComfyUI_mss_login.api import is_available, check_tensor_nsfw, ...",
		"except ImportError:",
		"    from mss-login.api import is_available, check_tensor_nsfw, ...",
		"```",
		"",
		"Always check `is_available()` before using other functions if the extension might be optional.",
		"",
		"---",
		"",
		"## Functions",
		"",
	]
	for name, sig, doc in entries:
		lines.append(f"### `{name}`")
		lines.append("")
		lines.append("```python")
		lines.append(sig)
		lines.append("```")
		lines.append("")
		if doc:
			lines.append(doc.strip())
			lines.append("")
		lines.append("---")
		lines.append("")
	lines.extend(["", "*Generated by `scripts/build_docs.py`.*"])
	out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
	os.chdir(ROOT)
	generate_endpoints_md()
	generate_nsfw_guard_api_md()
	print("Docs generated: api-reference/endpoints.md, extension-api/nsfw-guard-api.md")


if __name__ == "__main__":
	main()
