name: Publish to ComfyUI registry
on:
    workflow_dispatch:
    push:
        branches:
            - production
        paths:
            - "pyproject.toml"

permissions:
    contents: read
    packages: write
    id-token: write

concurrency:
    group: "publish"
    cancel-in-progress: true

jobs:
    publish:
        name: Publish to ComfyUI registry
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  path: ${{ github.workspace }}/ComfyUI-MSS-Login
                  lfs: true
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"
                  cache: "pip"
                  cache-dependency-path: ComfyUI-MSS-Login/pyproject.toml
            - name: Install uv
              run: pip install -U uv
            - run: uv sync --group comfyui
              working-directory: ComfyUI-MSS-Login
            - name: Publish ComfyUI Node
              working-directory: ${{ github.workspace }}/ComfyUI-MSS-Login
              env:
                  NODE_PATH: ${{ github.workspace }}/ComfyUI-MSS-Login
                  COMFY_NODE_NAME: MSS-Login
              run: uv run scripts/publish_comfy_node.py -D -v --node-name ${{ env.COMFY_NODE_NAME }} --node-path ${{ env.NODE_PATH }} --registry-access-token ${{ secrets.REGISTRY_ACCESS_TOKEN }}
